#Messages!

firstJoin_Msg: '&a Welcome <player>, to &eExampleServerName!'
join_Msg: '&b <player> &ajoined.'
leave_Msg: '&b <player> &cleft.'

#Enable and Disable Messages below.

firstJoin_enabled: true
join_enabled: true
leave_enabled: true
