#Messages!

firstJoin: '&a Welcome <player>, to our &eserver'
join: '&b<player> &ajoined.'
leave: '&b<player> &cleft.'

#Enable Messages

firstJoin_e: true
join_e: true
leave_e: true

#Exclude players

exclude: ['player_excluded_from_showing_join_and_leave_messages']
