name: HelloMSG
author: reversee
version: v2.1
main: me.reversee.HelloMSG
description: Displaying Chat Messages on Player First join, normal join and leave made easier!
api-version: 1.17

commands:
  hellomsg:
    description: do /hellomsg for help!
    permission: hellomsg.admin

permissions:
  hellomsg.admin:
    default: op

