name: HelloMsg
version: 1.3
author: Niplex
main: tk.niplex.hellomsg.Main
description: This plugin displays Chat Messages on Player First join, join and leave

commands:
  hellomsg:
    description: HelloMSG command
    useage: /hellomsg <reload|createconfig>
    permission: hellomsg.admin
  helloinvis:
    description: HelloMSG Incognito Mode allows Admins to make the plugin don't send join and leave message when them joins    
    useage: /helloinvis
    permission: hellomsg.admin
    
permissions:
  hellomsg.admin:
    default: op
  hellomsg.incognito:
    default: false